/* ============================================================
   CONTENU DES GALERIES — à compléter par Natan
   ------------------------------------------------------------
   Ajouter les photos dans le dossier /images puis une ligne par photo :
   { src: "images/portrait-01.jpg", thumb: "images/portrait-01-800.jpg", cat: "Portrait", alt: "Description courte" }

   Export Lightroom conseillé :
   - src   : JPEG sRGB, grand côté 2000 px, qualité 80, métadonnées copyright seulement
   - thumb : JPEG sRGB, grand côté 800 px, qualité 75 (optionnel, sinon src est utilisé)
   - Noms de fichiers en minuscules, sans espace ni accent (portrait-studio-01.jpg)

   Catégories utilisées pour les filtres : la valeur de "cat" (créées automatiquement).
   Import initial 2026-09-29 : 228 photos reprises du portfolio Adobe (1920 px sRGB q80, vignettes 900 px q75).
   Boudoir / Nu volontairement exclu de la galerie publique (annoncé comme galerie privée).
   ============================================================ */

window.PHOTOS = [
  { src: "images/createurs-collabs-01.jpg", thumb: "images/createurs-collabs-01-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 1" },
  { src: "images/createurs-collabs-02.jpg", thumb: "images/createurs-collabs-02-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 2" },
  { src: "images/createurs-collabs-03.jpg", thumb: "images/createurs-collabs-03-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 3" },
  { src: "images/createurs-collabs-04.jpg", thumb: "images/createurs-collabs-04-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 4" },
  { src: "images/createurs-collabs-05.jpg", thumb: "images/createurs-collabs-05-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 5" },
  { src: "images/createurs-collabs-06.jpg", thumb: "images/createurs-collabs-06-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 6" },
  { src: "images/createurs-collabs-07.jpg", thumb: "images/createurs-collabs-07-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 7" },
  { src: "images/createurs-collabs-08.jpg", thumb: "images/createurs-collabs-08-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 8" },
  { src: "images/createurs-collabs-09.jpg", thumb: "images/createurs-collabs-09-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 9" },
  { src: "images/createurs-collabs-10.jpg", thumb: "images/createurs-collabs-10-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 10" },
  { src: "images/createurs-collabs-11.jpg", thumb: "images/createurs-collabs-11-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 11" },
  { src: "images/createurs-collabs-12.jpg", thumb: "images/createurs-collabs-12-900.jpg", cat: "Créateurs", alt: "Créateurs – photo NatiShoot 12" },
  { src: "images/defile-01.jpg", thumb: "images/defile-01-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 1" },
  { src: "images/defile-02.jpg", thumb: "images/defile-02-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 2" },
  { src: "images/defile-03.jpg", thumb: "images/defile-03-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 3" },
  { src: "images/defile-04.jpg", thumb: "images/defile-04-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 4" },
  { src: "images/defile-05.jpg", thumb: "images/defile-05-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 5" },
  { src: "images/defile-06.jpg", thumb: "images/defile-06-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 6" },
  { src: "images/defile-07.jpg", thumb: "images/defile-07-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 7" },
  { src: "images/defile-08.jpg", thumb: "images/defile-08-900.jpg", cat: "Défilé", alt: "Défilé – photo NatiShoot 8" },
  { src: "images/portrait-01.jpg", thumb: "images/portrait-01-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 1" },
  { src: "images/portrait-02.jpg", thumb: "images/portrait-02-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 2" },
  { src: "images/portrait-03.jpg", thumb: "images/portrait-03-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 3" },
  { src: "images/portrait-04.jpg", thumb: "images/portrait-04-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 4" },
  { src: "images/portrait-05.jpg", thumb: "images/portrait-05-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 5" },
  { src: "images/portrait-06.jpg", thumb: "images/portrait-06-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 6" },
  { src: "images/portrait-07.jpg", thumb: "images/portrait-07-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 7" },
  { src: "images/portrait-08.jpg", thumb: "images/portrait-08-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 8" },
  { src: "images/portrait-09.jpg", thumb: "images/portrait-09-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 9" },
  { src: "images/portrait-10.jpg", thumb: "images/portrait-10-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 10" },
  { src: "images/portrait-11.jpg", thumb: "images/portrait-11-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 11" },
  { src: "images/portrait-12.jpg", thumb: "images/portrait-12-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 12" },
  { src: "images/portrait-13.jpg", thumb: "images/portrait-13-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 13" },
  { src: "images/portrait-14.jpg", thumb: "images/portrait-14-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 14" },
  { src: "images/portrait-15.jpg", thumb: "images/portrait-15-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 15" },
  { src: "images/portrait-16.jpg", thumb: "images/portrait-16-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 16" },
  { src: "images/portrait-17.jpg", thumb: "images/portrait-17-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 17" },
  { src: "images/portrait-18.jpg", thumb: "images/portrait-18-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 18" },
  { src: "images/portrait-19.jpg", thumb: "images/portrait-19-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 19" },
  { src: "images/portrait-20.jpg", thumb: "images/portrait-20-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 20" },
  { src: "images/portrait-21.jpg", thumb: "images/portrait-21-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 21" },
  { src: "images/portrait-22.jpg", thumb: "images/portrait-22-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 22" },
  { src: "images/portrait-23.jpg", thumb: "images/portrait-23-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 23" },
  { src: "images/portrait-24.jpg", thumb: "images/portrait-24-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 24" },
  { src: "images/portrait-25.jpg", thumb: "images/portrait-25-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 25" },
  { src: "images/portrait-26.jpg", thumb: "images/portrait-26-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 26" },
  { src: "images/portrait-27.jpg", thumb: "images/portrait-27-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 27" },
  { src: "images/portrait-28.jpg", thumb: "images/portrait-28-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 28" },
  { src: "images/portrait-29.jpg", thumb: "images/portrait-29-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 29" },
  { src: "images/portrait-30.jpg", thumb: "images/portrait-30-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 30" },
  { src: "images/portrait-31.jpg", thumb: "images/portrait-31-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 31" },
  { src: "images/portrait-32.jpg", thumb: "images/portrait-32-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 32" },
  { src: "images/portrait-33.jpg", thumb: "images/portrait-33-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 33" },
  { src: "images/portrait-34.jpg", thumb: "images/portrait-34-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 34" },
  { src: "images/portrait-35.jpg", thumb: "images/portrait-35-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 35" },
  { src: "images/portrait-36.jpg", thumb: "images/portrait-36-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 36" },
  { src: "images/portrait-37.jpg", thumb: "images/portrait-37-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 37" },
  { src: "images/portrait-38.jpg", thumb: "images/portrait-38-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 38" },
  { src: "images/portrait-39.jpg", thumb: "images/portrait-39-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 39" },
  { src: "images/portrait-40.jpg", thumb: "images/portrait-40-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 40" },
  { src: "images/portrait-41.jpg", thumb: "images/portrait-41-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 41" },
  { src: "images/portrait-42.jpg", thumb: "images/portrait-42-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 42" },
  { src: "images/portrait-43.jpg", thumb: "images/portrait-43-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 43" },
  { src: "images/portrait-44.jpg", thumb: "images/portrait-44-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 44" },
  { src: "images/portrait-45.jpg", thumb: "images/portrait-45-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 45" },
  { src: "images/portrait-46.jpg", thumb: "images/portrait-46-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 46" },
  { src: "images/portrait-47.jpg", thumb: "images/portrait-47-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 47" },
  { src: "images/portrait-48.jpg", thumb: "images/portrait-48-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 48" },
  { src: "images/portrait-49.jpg", thumb: "images/portrait-49-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 49" },
  { src: "images/portrait-50.jpg", thumb: "images/portrait-50-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 50" },
  { src: "images/portrait-51.jpg", thumb: "images/portrait-51-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 51" },
  { src: "images/portrait-52.jpg", thumb: "images/portrait-52-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 52" },
  { src: "images/portrait-53.jpg", thumb: "images/portrait-53-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 53" },
  { src: "images/portrait-54.jpg", thumb: "images/portrait-54-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 54" },
  { src: "images/portrait-55.jpg", thumb: "images/portrait-55-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 55" },
  { src: "images/portrait-56.jpg", thumb: "images/portrait-56-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 56" },
  { src: "images/portrait-57.jpg", thumb: "images/portrait-57-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 57" },
  { src: "images/portrait-58.jpg", thumb: "images/portrait-58-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 58" },
  { src: "images/portrait-59.jpg", thumb: "images/portrait-59-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 59" },
  { src: "images/portrait-60.jpg", thumb: "images/portrait-60-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 60" },
  { src: "images/portrait-61.jpg", thumb: "images/portrait-61-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 61" },
  { src: "images/portrait-62.jpg", thumb: "images/portrait-62-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 62" },
  { src: "images/portrait-63.jpg", thumb: "images/portrait-63-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 63" },
  { src: "images/portrait-64.jpg", thumb: "images/portrait-64-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 64" },
  { src: "images/portrait-65.jpg", thumb: "images/portrait-65-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 65" },
  { src: "images/portrait-66.jpg", thumb: "images/portrait-66-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 66" },
  { src: "images/portrait-67.jpg", thumb: "images/portrait-67-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 67" },
  { src: "images/portrait-68.jpg", thumb: "images/portrait-68-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 68" },
  { src: "images/portrait-69.jpg", thumb: "images/portrait-69-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 69" },
  { src: "images/portrait-70.jpg", thumb: "images/portrait-70-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 70" },
  { src: "images/portrait-71.jpg", thumb: "images/portrait-71-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 71" },
  { src: "images/portrait-72.jpg", thumb: "images/portrait-72-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 72" },
  { src: "images/portrait-73.jpg", thumb: "images/portrait-73-900.jpg", cat: "Portrait", alt: "Portrait – photo NatiShoot 73" },
  { src: "images/grossesse-01.jpg", thumb: "images/grossesse-01-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 1" },
  { src: "images/grossesse-02.jpg", thumb: "images/grossesse-02-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 2" },
  { src: "images/grossesse-03.jpg", thumb: "images/grossesse-03-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 3" },
  { src: "images/grossesse-04.jpg", thumb: "images/grossesse-04-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 4" },
  { src: "images/grossesse-05.jpg", thumb: "images/grossesse-05-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 5" },
  { src: "images/grossesse-06.jpg", thumb: "images/grossesse-06-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 6" },
  { src: "images/grossesse-07.jpg", thumb: "images/grossesse-07-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 7" },
  { src: "images/grossesse-08.jpg", thumb: "images/grossesse-08-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 8" },
  { src: "images/grossesse-09.jpg", thumb: "images/grossesse-09-900.jpg", cat: "Grossesse", alt: "Grossesse – photo NatiShoot 9" },
  { src: "images/cosplay-01.jpg", thumb: "images/cosplay-01-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 1" },
  { src: "images/cosplay-02.jpg", thumb: "images/cosplay-02-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 2" },
  { src: "images/cosplay-03.jpg", thumb: "images/cosplay-03-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 3" },
  { src: "images/cosplay-04.jpg", thumb: "images/cosplay-04-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 4" },
  { src: "images/cosplay-05.jpg", thumb: "images/cosplay-05-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 5" },
  { src: "images/cosplay-06.jpg", thumb: "images/cosplay-06-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 6" },
  { src: "images/cosplay-07.jpg", thumb: "images/cosplay-07-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 7" },
  { src: "images/cosplay-08.jpg", thumb: "images/cosplay-08-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 8" },
  { src: "images/cosplay-09.jpg", thumb: "images/cosplay-09-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 9" },
  { src: "images/cosplay-10.jpg", thumb: "images/cosplay-10-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 10" },
  { src: "images/cosplay-11.jpg", thumb: "images/cosplay-11-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 11" },
  { src: "images/cosplay-12.jpg", thumb: "images/cosplay-12-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 12" },
  { src: "images/cosplay-13.jpg", thumb: "images/cosplay-13-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 13" },
  { src: "images/cosplay-14.jpg", thumb: "images/cosplay-14-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 14" },
  { src: "images/cosplay-15.jpg", thumb: "images/cosplay-15-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 15" },
  { src: "images/cosplay-16.jpg", thumb: "images/cosplay-16-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 16" },
  { src: "images/cosplay-17.jpg", thumb: "images/cosplay-17-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 17" },
  { src: "images/cosplay-18.jpg", thumb: "images/cosplay-18-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 18" },
  { src: "images/cosplay-19.jpg", thumb: "images/cosplay-19-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 19" },
  { src: "images/cosplay-20.jpg", thumb: "images/cosplay-20-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 20" },
  { src: "images/cosplay-21.jpg", thumb: "images/cosplay-21-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 21" },
  { src: "images/cosplay-22.jpg", thumb: "images/cosplay-22-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 22" },
  { src: "images/cosplay-23.jpg", thumb: "images/cosplay-23-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 23" },
  { src: "images/cosplay-24.jpg", thumb: "images/cosplay-24-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 24" },
  { src: "images/cosplay-25.jpg", thumb: "images/cosplay-25-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 25" },
  { src: "images/cosplay-26.jpg", thumb: "images/cosplay-26-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 26" },
  { src: "images/cosplay-27.jpg", thumb: "images/cosplay-27-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 27" },
  { src: "images/cosplay-28.jpg", thumb: "images/cosplay-28-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 28" },
  { src: "images/cosplay-29.jpg", thumb: "images/cosplay-29-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 29" },
  { src: "images/cosplay-30.jpg", thumb: "images/cosplay-30-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 30" },
  { src: "images/cosplay-31.jpg", thumb: "images/cosplay-31-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 31" },
  { src: "images/cosplay-32.jpg", thumb: "images/cosplay-32-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 32" },
  { src: "images/cosplay-33.jpg", thumb: "images/cosplay-33-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 33" },
  { src: "images/cosplay-34.jpg", thumb: "images/cosplay-34-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 34" },
  { src: "images/cosplay-35.jpg", thumb: "images/cosplay-35-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 35" },
  { src: "images/cosplay-36.jpg", thumb: "images/cosplay-36-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 36" },
  { src: "images/cosplay-37.jpg", thumb: "images/cosplay-37-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 37" },
  { src: "images/cosplay-38.jpg", thumb: "images/cosplay-38-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 38" },
  { src: "images/cosplay-39.jpg", thumb: "images/cosplay-39-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 39" },
  { src: "images/cosplay-40.jpg", thumb: "images/cosplay-40-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 40" },
  { src: "images/cosplay-41.jpg", thumb: "images/cosplay-41-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 41" },
  { src: "images/cosplay-42.jpg", thumb: "images/cosplay-42-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 42" },
  { src: "images/cosplay-43.jpg", thumb: "images/cosplay-43-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 43" },
  { src: "images/cosplay-44.jpg", thumb: "images/cosplay-44-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 44" },
  { src: "images/cosplay-45.jpg", thumb: "images/cosplay-45-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 45" },
  { src: "images/cosplay-46.jpg", thumb: "images/cosplay-46-900.jpg", cat: "Cosplay", alt: "Cosplay – photo NatiShoot 46" },
  { src: "images/concerts-01.jpg", thumb: "images/concerts-01-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 1" },
  { src: "images/concerts-02.jpg", thumb: "images/concerts-02-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 2" },
  { src: "images/concerts-03.jpg", thumb: "images/concerts-03-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 3" },
  { src: "images/concerts-04.jpg", thumb: "images/concerts-04-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 4" },
  { src: "images/concerts-05.jpg", thumb: "images/concerts-05-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 5" },
  { src: "images/concerts-06.jpg", thumb: "images/concerts-06-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 6" },
  { src: "images/concerts-07.jpg", thumb: "images/concerts-07-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 7" },
  { src: "images/concerts-08.jpg", thumb: "images/concerts-08-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 8" },
  { src: "images/concerts-09.jpg", thumb: "images/concerts-09-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 9" },
  { src: "images/concerts-10.jpg", thumb: "images/concerts-10-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 10" },
  { src: "images/concerts-11.jpg", thumb: "images/concerts-11-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 11" },
  { src: "images/concerts-12.jpg", thumb: "images/concerts-12-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 12" },
  { src: "images/concerts-13.jpg", thumb: "images/concerts-13-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 13" },
  { src: "images/concerts-14.jpg", thumb: "images/concerts-14-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 14" },
  { src: "images/concerts-15.jpg", thumb: "images/concerts-15-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 15" },
  { src: "images/concerts-16.jpg", thumb: "images/concerts-16-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 16" },
  { src: "images/concerts-17.jpg", thumb: "images/concerts-17-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 17" },
  { src: "images/concerts-18.jpg", thumb: "images/concerts-18-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 18" },
  { src: "images/concerts-19.jpg", thumb: "images/concerts-19-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 19" },
  { src: "images/concerts-20.jpg", thumb: "images/concerts-20-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 20" },
  { src: "images/concerts-21.jpg", thumb: "images/concerts-21-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 21" },
  { src: "images/concerts-22.jpg", thumb: "images/concerts-22-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 22" },
  { src: "images/concerts-23.jpg", thumb: "images/concerts-23-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 23" },
  { src: "images/concerts-24.jpg", thumb: "images/concerts-24-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 24" },
  { src: "images/concerts-25.jpg", thumb: "images/concerts-25-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 25" },
  { src: "images/concerts-26.jpg", thumb: "images/concerts-26-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 26" },
  { src: "images/concerts-27.jpg", thumb: "images/concerts-27-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 27" },
  { src: "images/concerts-28.jpg", thumb: "images/concerts-28-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 28" },
  { src: "images/concerts-29.jpg", thumb: "images/concerts-29-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 29" },
  { src: "images/concerts-30.jpg", thumb: "images/concerts-30-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 30" },
  { src: "images/concerts-31.jpg", thumb: "images/concerts-31-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 31" },
  { src: "images/concerts-32.jpg", thumb: "images/concerts-32-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 32" },
  { src: "images/concerts-33.jpg", thumb: "images/concerts-33-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 33" },
  { src: "images/concerts-34.jpg", thumb: "images/concerts-34-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 34" },
  { src: "images/concerts-35.jpg", thumb: "images/concerts-35-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 35" },
  { src: "images/concerts-36.jpg", thumb: "images/concerts-36-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 36" },
  { src: "images/concerts-37.jpg", thumb: "images/concerts-37-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 37" },
  { src: "images/concerts-38.jpg", thumb: "images/concerts-38-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 38" },
  { src: "images/concerts-39.jpg", thumb: "images/concerts-39-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 39" },
  { src: "images/concerts-40.jpg", thumb: "images/concerts-40-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 40" },
  { src: "images/concerts-41.jpg", thumb: "images/concerts-41-900.jpg", cat: "Concerts", alt: "Concerts – photo NatiShoot 41" },
  { src: "images/manifestation-01.jpg", thumb: "images/manifestation-01-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 1" },
  { src: "images/manifestation-02.jpg", thumb: "images/manifestation-02-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 2" },
  { src: "images/manifestation-03.jpg", thumb: "images/manifestation-03-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 3" },
  { src: "images/manifestation-04.jpg", thumb: "images/manifestation-04-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 4" },
  { src: "images/manifestation-05.jpg", thumb: "images/manifestation-05-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 5" },
  { src: "images/manifestation-06.jpg", thumb: "images/manifestation-06-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 6" },
  { src: "images/manifestation-07.jpg", thumb: "images/manifestation-07-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 7" },
  { src: "images/manifestation-08.jpg", thumb: "images/manifestation-08-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 8" },
  { src: "images/manifestation-09.jpg", thumb: "images/manifestation-09-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 9" },
  { src: "images/manifestation-10.jpg", thumb: "images/manifestation-10-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 10" },
  { src: "images/manifestation-11.jpg", thumb: "images/manifestation-11-900.jpg", cat: "Manifestations", alt: "Manifestations – photo NatiShoot 11" },
  { src: "images/sport-01.jpg", thumb: "images/sport-01-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 1" },
  { src: "images/sport-02.jpg", thumb: "images/sport-02-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 2" },
  { src: "images/sport-03.jpg", thumb: "images/sport-03-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 3" },
  { src: "images/sport-04.jpg", thumb: "images/sport-04-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 4" },
  { src: "images/sport-05.jpg", thumb: "images/sport-05-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 5" },
  { src: "images/sport-06.jpg", thumb: "images/sport-06-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 6" },
  { src: "images/sport-07.jpg", thumb: "images/sport-07-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 7" },
  { src: "images/sport-08.jpg", thumb: "images/sport-08-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 8" },
  { src: "images/sport-09.jpg", thumb: "images/sport-09-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 9" },
  { src: "images/sport-10.jpg", thumb: "images/sport-10-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 10" },
  { src: "images/sport-11.jpg", thumb: "images/sport-11-900.jpg", cat: "Sport", alt: "Sport – photo NatiShoot 11" },
  { src: "images/divers-01.jpg", thumb: "images/divers-01-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 1" },
  { src: "images/divers-02.jpg", thumb: "images/divers-02-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 2" },
  { src: "images/divers-03.jpg", thumb: "images/divers-03-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 3" },
  { src: "images/divers-04.jpg", thumb: "images/divers-04-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 4" },
  { src: "images/divers-05.jpg", thumb: "images/divers-05-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 5" },
  { src: "images/divers-06.jpg", thumb: "images/divers-06-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 6" },
  { src: "images/divers-07.jpg", thumb: "images/divers-07-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 7" },
  { src: "images/divers-08.jpg", thumb: "images/divers-08-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 8" },
  { src: "images/divers-09.jpg", thumb: "images/divers-09-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 9" },
  { src: "images/divers-10.jpg", thumb: "images/divers-10-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 10" },
  { src: "images/divers-11.jpg", thumb: "images/divers-11-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 11" },
  { src: "images/divers-12.jpg", thumb: "images/divers-12-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 12" },
  { src: "images/divers-13.jpg", thumb: "images/divers-13-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 13" },
  { src: "images/divers-14.jpg", thumb: "images/divers-14-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 14" },
  { src: "images/divers-15.jpg", thumb: "images/divers-15-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 15" },
  { src: "images/divers-16.jpg", thumb: "images/divers-16-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 16" },
  { src: "images/divers-17.jpg", thumb: "images/divers-17-900.jpg", cat: "Divers", alt: "Divers – photo NatiShoot 17" }
];

/* Séries = galeries du portfolio Adobe (liens conservés en attendant la migration complète) */
window.SERIES = [
  { name: "Créateurs (Collabs)", year: 2026, url: "https://natishoot.myportfolio.com/createurs-collabs" },
  { name: "Défilé / Mode", year: 2026, url: "https://natishoot.myportfolio.com/defile" },
  { name: "Vidéos NatiShoot", year: 2026, url: "https://natishoot.myportfolio.com/videos-natishoot" },
  { name: "Portrait", year: 2025, url: "https://natishoot.myportfolio.com/portrait" },
  { name: "Grossesse", year: 2025, url: "https://natishoot.myportfolio.com/grossesse" },
  { name: "Cosplay", year: 2025, url: "https://natishoot.myportfolio.com/cosplay" },
  { name: "Concerts", year: 2025, url: "https://natishoot.myportfolio.com/concerts" },
  { name: "Manifestations", year: 2025, url: "https://natishoot.myportfolio.com/manifestation" },
  { name: "Sport", year: 2025, url: "https://natishoot.myportfolio.com/sport" },
  { name: "Boudoir / Nu", year: 2025, url: "https://natishoot.myportfolio.com/boudoir" },
  { name: "Divers", year: 2025, url: "https://natishoot.myportfolio.com/divers" }
];
